version: 2.1

jobs:
  build:
    macos:
      xcode: "10.1.0"
    environment:
      GOPATH: /Users/distiller/go
      GOROOT: /usr/local/go
      BREWBIN: /usr/local/opt/go/bin
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            yarn install
      - run:
          name: lint sources
          command: |
            yarn lint
      - run:
          name: build binaries
          command: |
            yarn dist --macos --windows --linux
      - run:
          name: collect artifacts
          command: |
            VERSION=v$(node -p "require('./package.json').version")
            if [ "${CIRCLE_TAG}" != "" ]; then
                VERSION=${CIRCLE_TAG}
            fi
            OUT=~/output
            mkdir -p ${OUT}
            mv ~/project/dist/TextilePhotos-${VERSION}.{dmg,exe,AppImage,pkg,snap} ${OUT}/
      - persist_to_workspace:
          root: ~/
          paths:
            - output
      - store_artifacts:
          path: ~/output

  release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - deploy:
          name: release binaries
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ~/output/
workflows:
  version: 2
  photos-desktop:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/